### ISSUE TITLE
duplicated react-native

### ISSUE THREAD

**Issue by oakcreations** [digital-waterfall/rn-multi-tenant-async-storage#1]
warning: the transform cache was reset.
Loading dependency graph...(node:24585) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: /Users/infra/Documents/project/medcelareadoalunov4/node_modules/rn-multi-tenant-async-storage/node_modules/react-native/package.json collides with /Users/infra/Documents/project/medcelareadoalunov4/node_modules/react-native/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/infra/Documents/project/medcelareadoalunov4/node_modules/jest-haste-map/build/index.js:551:17)
    at workerReply (/Users/infra/Documents/project/medcelareadoalunov4/node_modules/jest-haste-map/build/index.js:613:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:24585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejectinga promise which was not handled with .catch(). (rejection id: 2)
(node:24585) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24585) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: /Users/infra/Documents/project/medcelareadoalunov4/node_modules/rn-multi-tenant-async-storage/node_modules/react-native/package.json collides with /Users/infra/Documents/project/medcelareadoalunov4/node_modules/react-native/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/infra/Documents/project/medcelareadoalunov4/node_modules/jest-haste-map/build/index.js:551:17)
    at workerReply (/Users/infra/Documents/project/medcelareadoalunov4/node_modules/jest-haste-map/build/index.js:613:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:24585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejectinga promise which was not handled with .catch(). (rejection id: 3)

**Comment by craig95** [comment]
Will fix the package.json within the next day to fix this issue.

**Comment by craig95** [comment]
Pushed a fix.
